---
title: "Report"
author: "Rutuja"
date: "2025-03-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(MASS)
 
print("loading data")
d <- read.delim("/outs/the_greater_big_data_file_bigger.txt", header=TRUE, sep=" ")
print("loaded data. running models. breathe.")

d$rep.fitted <- (d$rep.fitted.dip + d$rep.fitted.hap)/2
d$collision <- (d$collision.dip + d$collision.hap)/2

# d <- d %>% filter(transcripts < 15)
d <- d %>% filter(transcripts < 2.5e4)

head(d)
```

```{r}
hist(d$transcripts[is.na(d$length)])
```

```{r}
table(is.na(d$length), is.na(d$distance))
```

```{r}
table(is.na(d$length), d$SNM)
```

```{r}
f1 = 2747
f2 = 11161457
  
m1 = 212
m2 = 839013

p_hat_F <- f1/(f1+f2)
n_F <- (f1+f2)
p_hat_M <- m1/(m1+m2)
n_M <- (m1+m2)

# Calculate common proportion
p_hat <- (p_hat_F*n_F + p_hat_M*n_M) / (n_F + n_M)

# Check whether our sample sizes are large enough
n_F*p_hat; n_F*(1-p_hat)
n_M*p_hat; n_M*(1-p_hat)

# Calculate test statistic
z_obs <- (p_hat_F - p_hat_M - 0) / sqrt(p_hat*(1-p_hat)*(1/n_M + 1/n_F))

# Find 0.05-level rejection region
qnorm(0.025)
qnorm(1-0.025)

# Calculate p-value
2*(1-pnorm(z_obs, lower.tail = F))
```

```{r}
d %>% ggplot() +
  geom_boxplot(aes(x=is.na(length), y=rep.fitted, color=SNM))
```

```{r}
d %>% filter(SNM) %>% ggplot() +
  stat_ecdf(aes(color=is.na(length), x=2-rep.fitted), geom = "step") +
  stat_ecdf(aes(x=2-rep.fitted), color="grey", geom = "step") 
```

```{r}
t1 <- t.test(d$rep.fitted[is.na(d$length) & d$SNM], d$rep.fitted[is.na(d$length) & !d$SNM])
t1
t2 <- t.test(d$rep.fitted[!is.na(d$length) & d$SNM], d$rep.fitted[!is.na(d$length) & !d$SNM])
t2
```

```{r}
cumul<-function(x, n=50, start=0, stop=1){x<-na.omit(x);sapply(seq(start,stop,length.out=n),function(i){length(x[x<=i])/length(x)})}
    bt<-function(v,reps=5000){sapply(c(1:reps),function(i){mean(sample(na.omit(v),replace=T))})}
    
rep.sample <- sample(d$rep.fitted[ d$SNM], 3000, replace=TRUE)
# rep.sample <- sample(seq(1,2, 0.001), 3000, replace=TRUE)
    
c.hap.obs<-cumul(2-d$rep.fitted[is.na(d$length) & d$SNM])
c.dip.obs<-cumul(2-d$rep.fitted[!is.na(d$length) & d$SNM])
c.rand<-cumul(2-rep.sample)
ratio.seq<-seq(0,1,length.out=50)
bt.hap.obs<-bt(2-d$rep.fitted[is.na(d$length) & d$SNM])
bt.dip.obs<-bt(2-d$rep.fitted[!is.na(d$length) & d$SNM])
bt.rand<-bt(2-rep.sample)
    
plot.means<-c(mean(2-rep.sample,na.rm=T),
              mean(2-d$rep.fitted[is.na(d$length) & d$SNM],na.rm=T),
              mean(2-d$rep.fitted[!is.na(d$length) & d$SNM],na.rm=T))
plot.lwr<-as.numeric(c(quantile(bt.rand,0.025),
  quantile(bt.hap.obs,0.025),quantile(bt.dip.obs,0.025)))
plot.upr<-as.numeric(c(quantile(bt.rand,0.975),
  quantile(bt.hap.obs,0.975),quantile(bt.dip.obs,0.975)))
```

```{r}
mycol = c("red", "red", "blue", "blue")
# par<-opar
par(mar=c(0,0,0,0)+0.1,fig=c(0.1,0.47,0.55,0.95))
plot(c.rand~ratio.seq, type="l", col="gray",lwd=1.5,las=1,xlab="",ylab="",cex.axis=0.8,xaxt="n")
axis(1,cex.axis=0.8,padj=-1,tck=-0.05)
points(c.hap.obs~ratio.seq, type="l", col=mycol[1],lwd=1.5)
points(c.dip.obs~ratio.seq, type="l", col=mycol[3],lwd=1.5)
text(-0.22,0.5,"Cumulative fraction of variants",cex=0.75,srt=90,xpd=NA)
text(0.5,-0.25,"DNA replication timing",cex=0.75,xpd=NA)
text(c(0,1),c(-0.25,-0.25),c("Earlier","Later"),cex=0.6,xpd=NA)
text(rep(0,3),c(0.85,0.75,0.65),c("Random","Unannotated","Annotated"),cex=0.75, pos=4, col=c("gray",mycol[2:3]))
    
par(fig=c(0.37,0.465,0.555,0.72),new=T)
```


```{r}
# par(fig=c(0.37,0.465,0.555,0.72),new=T)
par(mar=c(0,0,0,0)+0.1,fig=c(0.1,0.47,0.25,0.85))

plot(plot.means~c(1:3),
     xlim=c(0,4),ylim=c(0.49,0.70),
     col=c("gray",mycol[2:3]),pch=16,xaxt="n",yaxt="n",xlab="",ylab="",cex=0.6)
arrows(c(1:3),plot.lwr,c(1:3),plot.upr,col=c("gray",mycol[2:3]),length=0.04,code=3,angle=90)
axis(2,at=seq(0,1,0.02),hadj=0.1,cex.axis=0.5,tck=-0.01,las=1)
text(-1.9,0.532,"Mean timing (95%CI)", cex=0.6, srt=90,xpd=NA)
```


```{r}
d %>% filter(SNM) %>% ggplot() +
  stat_ecdf(aes(color=is.na(length), x=2-rep.fitted), geom = "step") +
  stat_ecdf(data=data.frame(random=seq(0,1,0.002)), aes(x=random), color="grey", geom = "step") 
```

```{r}
d %>% filter(!is.na(distance)) %>% ggplot() +
  geom_density(aes(x=distance, color=SNM))
```

```{r}
t2 <- t.test((d$distance[!is.na(d$length) & d$SNM])^2, (d$distance[!is.na(d$length) & !d$SNM])^2)
t2
```

```{r}
hist(d$distance)
```

```{r}
d %>% filter(!is.na(distance)) %>% ggplot() +
  geom_point(aes(x=SNM, y=distance))
```


```{r}
mod <- glm(formula = SNM ~ base.type + rep.fitted + protein + distance + 
    collision + I(distance^2) + distance:collision + transcripts:length + 
    protein:distance + base.type:distance + base.type:collision, 
    family = "binomial", data = d)
summary(mod)
```
```{r}
coeff <- summary(mod)$coefficients

coeffs <- data.frame(Coefficients = (coeff[-1,1]), Predictors=rownames(coeff)[-1])
coeffs %>%
  arrange(Coefficients) %>%
  ggplot() +
  geom_col(aes(y=Coefficients, x=fct_reorder(Predictors, Coefficients, .desc = TRUE))) +
  theme(text = element_text(size = 15),
        axis.text.x = element_text(angle = 90, hjust = 1)) +
  xlab("Predictors")
```


```{r}
#coeffs$PVE <- c(0.8669414,2,3,4,5,6,7,8,9,10,11,12,13,14)
coeffs <- data.frame(Predictors = c("base.type", "rep.fitted", "protein", "distance", "collision", "distance^2", "distance:collision", "transcripts:length", "protein:distance", "base.type:distance", "base.type:collision"),
                     PVE = c(0.8669414,0.01976554,0.0678921,0.05402601,0.0207636,0.008077868,0.003516638,
                             0.00368679,0.02515068,0.01279865,0.005247945))

coeffs <- data.frame(Predictors = c("rep.fitted", "protein", "distance", "collision", "distance^2", "distance:collision", "transcripts:length", "protein:distance", "base.type:distance", "base.type:collision"),
                     PVE = c(0.01976554,0.0678921,0.05402601,0.0207636,0.008077868,0.003516638,
                             0.00368679,0.02515068,0.01279865,0.005247945))
coeffs

coeffs %>%
  ggplot() +
  geom_col(aes(y=PVE*100, x=fct_reorder(Predictors, PVE, .desc = TRUE))) +
  theme(text = element_text(size = 18),
        axis.text.x = element_text(angle = 90, hjust = 1)) +
  ylab("PVE") +
  xlab("Predictors")
```

```{r}
d %>% 
  # filter(distance < 5e3) %>% 
  ggplot() +
  # geom_density(aes(x=distance, color=protein, linetype=SNM)) +
  stat_ecdf(aes(x=distance, color=protein, linetype=SNM)) +
  xlim(c(0,5e3)) + 
  ylab("Cumulative Density") +
  xlab("Distance") +
  theme(text = element_text(size = 18))
```

```{r}
d %>% 
  # filter(distance < 5e3) %>% 
  filter(!protein) %>%
  ggplot() +
  # geom_density(aes(x=distance, color=protein, linetype=SNM)) +
  stat_ecdf(aes(x=distance, color=protein, linetype=SNM)) +
  xlim(c(0,5e3)) + 
  ylab("Cumulative Density") +
  xlab("Distance")
```


```{r}
predicted <- predict(mod, type="response")
t <- d %>% filter(!is.na(distance))
t$predict_SNM <- predicted 
```


```{r}
q <- t %>% 
  group_by(G = cut(predict_SNM, breaks=unique(quantile(predict_SNM, probs=seq(0, 1, by=0.0001))))) %>%
  summarize(predicted = mean(predict_SNM), rep.fitted = mean(rep.fitted), 
            transcripts = mean(transcripts), count=n())
# q
nrow(q)
# cor(q$predicted, q$observed)
q %>% 
  ggplot(aes(x=transcripts+1, y=2-rep.fitted, z=predicted)) + 
  # geom_hex(aes(fill=predict_dip.SNM))
  # ggplot(diamonds, aes(x = x, y = price, z = depth)) +
  stat_summary_hex(fun = mean, bins = 30, show.legend = TRUE) +
  # stat_summary_hex(fun=function(z){log(mean(z))}, bins=25) +
  scale_fill_gradientn(colors=rev(viridis(20)), guide=guide_colorbar(title="Mutation")) +
  # scale_fill_continuous(type = "viridis") +
  # scale_fill_gradientn(colors=rev(rainbow(6))) +
  # facet_grid(cols = vars(protein),
  #            rows = vars(base.type), labeller = label_both)  +
  scale_x_log10() +
  xlab("Transcription Level") +
  ylab("Replication Timing") +
  theme(text = element_text(size = 18))
```


```{r}

q <- t %>% 
  group_by(G = cut(predict_SNM, breaks=unique(quantile(predict_SNM, probs=seq(0, 1, by=0.01))))) %>%
  summarize(predicted = mean(predict_SNM), observed = mean(SNM), count=n())
# q
nrow(q)
cor(q$predicted, q$observed)
q %>% ggplot() +
  geom_point(aes(y=observed, x=predicted)) +
  geom_smooth(aes(y=observed, x=predicted), method="lm", se=FALSE, color="red") +
  # geom_abline(slope=1, intercept=0, color="red") +
  xlab("Expected mutations in quantile") +
  ylab("Observed mutations in quantile") +
  theme(text = element_text(size = 18)) 
  
```

